HOST=learn
PROD_PATH=~/learn.avdi.codes
PROD=${HOST}:${PROD_PATH}
PLUGIN_NAME=learndotavdidotcodes
THEME_NAME=learndotavdidotcodes
PLUGIN_SEGMENT=wp-content/plugins/${PLUGIN_NAME}
THEME_SEGMENT=wp-content/themes/${THEME_NAME}
REMOTE_PLUGIN_PATH=${PROD}/${PLUGIN_SEGMENT}
LOCAL_PLUGIN_PATH=./${PLUGIN_SEGMENT}
REMOTE_THEME_PATH=${PROD}/${THEME_SEGMENT}
LOCAL_THEME_PATH=./${THEME_SEGMENT}

.PHONY: deploy

deploy:
	scp -r ${LOCAL_PLUGIN_PATH}/* ${REMOTE_PLUGIN_PATH}/
	scp -r ${LOCAL_THEME_PATH}/* ${REMOTE_THEME_PATH}/

pull:
	scp -r ${REMOTE_PLUGIN_PATH}/* ${LOCAL_PLUGIN_PATH}
	scp -r ${REMOTE_THEME_PATH}/* ${LOCAL_THEME_PATH}